spring:
  application:
    name: loan-simulation

  config:
    import: optional:configserver:http://localhost:8888

  profiles:
    active: dev

  cloud:
    config:
      fail-fast: true
      retry:
        # retry configuration retrieval up to 100 times
        max-attempts: 30
        # max backoff interval
        max-interval: 8000
